openapi: 3.1.0
info:
  version: 0.0.1
  title: OpenAPI Sample
  description:
    $ref: ./README.md
servers:
  - url: "https://api.example.com"
    description: Production Server
paths:
  /users:
    $ref: ./paths/users.yaml
  "/users/{id}":
    $ref: "./paths/users.{id}.yaml"
components:
  schemas:
    User:
      $ref: ./components/schemas/User.yaml
    EnumStatus:
      $ref: ./components/schemas/EnumStatus.yaml
    RequestPostUsers:
      $ref: ./components/schemas/RequestPostUsers.yaml
    RequestPutUserId:
      $ref: ./components/schemas/RequestPutUserId.yaml
    ResponseError:
      $ref: ./components/schemas/ResponseError.yaml
    ResponseGetUsers:
      $ref: ./components/schemas/ResponseGetUsers.yaml
    ResponseGetUsersId:
      $ref: ./components/schemas/ResponseGetUsersId.yaml
