openapi: 3.1.0
info:
  version: 0.0.1
  title: OpenAPI Sample
  description:
    $ref: ./description.md
servers:
  - url: "https://api.example.com"
    description: Production Server
paths:
  /users:
    $ref: ./components/paths/users.yaml
  "/users/{id}":
    $ref: "./components/paths/users.{id}.yaml"
components:
  schemas:
    User:
      $ref: ./components/schemas/models/User.yaml
    EnumStatus:
      $ref: ./components/schemas/enums/Status.yaml
    RequestPostUsers:
      $ref: ./components/schemas/requests/PostUsers.yaml
    RequestPutUserId:
      $ref: ./components/schemas/requests/PutUserId.yaml
    ResponseError:
      $ref: ./components/schemas/responses/Error.yaml
    ResponseGetUsers:
      $ref: ./components/schemas/responses/GetUsers.yaml
    ResponseGetUsersId:
      $ref: ./components/schemas/responses/GetUsersId.yaml
